//! Turning the registry JSON into the static tables `one-saves-registry` ships.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::registry::{Clocks, Registries};

/// A Rust string literal.
fn lit(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

/// A Rust slice of string literals.
fn lits(items: &[String]) -> String {
    format!("&[{}]", items.iter().map(|i| lit(i)).collect::<Vec<_>>().join(", "))
}

/// Writes one static table: a doc comment, the array header, a row per item, and the close.
fn table<T>(w: &mut String, doc: &str, name: &str, ty: &str, items: &[T], row: impl Fn(&T) -> String) {
    writeln!(w, "/// {doc}").unwrap();
    writeln!(w, "pub(crate) static {name}: [{ty}; {}] = [", items.len()).unwrap();
    for item in items {
        writeln!(w, "    {},", row(item)).unwrap();
    }
    writeln!(w, "];\n").unwrap();
}

/// The const name a slug takes in the `cores` and `systems` modules: upper snake case, and never
/// leading with a digit, since `3do-mister` is a perfectly good slug and not a Rust identifier.
fn const_name(slug: &str) -> String {
    let body: String =
        slug.chars().map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' }).collect();
    if body.starts_with(|c: char| c.is_ascii_digit()) { format!("_{body}") } else { body }
}

/// The const names for a set of slugs, refusing any pair that collide.
///
/// Two slugs that differ only where `const_name` does not would emit the same const twice. rustc
/// would catch it, but in generated code and with nothing pointing back at the slugs that caused it.
fn const_names<'a>(slugs: impl Iterator<Item = &'a str>) -> Result<Vec<String>, String> {
    let mut seen: BTreeMap<String, &str> = BTreeMap::new();
    let mut out = Vec::new();
    for slug in slugs {
        let name = const_name(slug);
        if let Some(first) = seen.insert(name.clone(), slug) {
            return Err(format!("{first:?} and {slug:?} both want the const {name}"));
        }
        out.push(name);
    }
    Ok(out)
}

/// The `ClockLayout` expression for one core, or `None` where the file records nothing.
fn clock(slug: &str, clocks: &Clocks) -> Result<String, String> {
    let Some(entry) = clocks.cores.get(slug) else { return Ok("None".to_owned()) };
    match (entry.layout.as_str(), entry.reserved) {
        ("appended", None) => Ok("Some(ClockLayout::Appended)".to_owned()),
        ("sidecar", None) => Ok("Some(ClockLayout::Sidecar)".to_owned()),
        ("packed", Some(n)) => Ok(format!("Some(ClockLayout::Packed {{ reserved: {n} }})")),
        ("packed", None) => Err(format!("clocks.json: {slug:?} is packed but sets no reserved length")),
        (other, _) => Err(format!("clocks.json: {slug:?} has unknown layout {other:?}")),
    }
}

fn core_kind(kind: &str) -> Result<&'static str, String> {
    match kind {
        "libretro" => Ok("Libretro"),
        "mister" => Ok("MiSTer"),
        "openfpga" => Ok("OpenFpga"),
        other => Err(format!("{other:?} is not a core kind")),
    }
}

/// Writes the generated tables, then formats them so the file is byte-stable.
///
/// Formatting here rather than leaving it to a later `cargo fmt` is what lets CI regenerate and
/// diff: without it the sync check and the format check would contradict each other.
///
/// The per-registry emitters are separate functions below; the seams are where one registry ends
/// and the next begins, which is the one place the data does have one.
pub fn write_rust(data: &Registries, clocks: &Clocks, path: &Path) -> Result<(), String> {
    // A clock layout naming a core that is not listed is a typo rather than a new core, and it
    // would otherwise vanish silently: nothing downstream reads this file by any other route.
    for slug in clocks.cores.keys() {
        if !data.cores.iter().any(|c| &c.slug == slug) {
            return Err(format!("clocks.json: {slug:?} is not a listed core"));
        }
    }

    // A core kind that is not one of the three is a registry change this generator has not been
    // taught, so it is checked before anything is written rather than producing a file that will
    // not compile.
    let kinds: Vec<&str> = data.cores.iter().map(|c| core_kind(&c.kind)).collect::<Result<_, _>>()?;

    let mut out = String::new();
    let w = &mut out;
    writeln!(w, "// @generated by `cargo xtask registries`. Do not edit by hand.").unwrap();
    writeln!(w, "//").unwrap();
    writeln!(w, "// The JSON under `data/` is itself synced from the registry pages at docs.1retro.com,")
        .unwrap();
    writeln!(w, "// so a change starts there, lands in the JSON, and reaches this file last.").unwrap();
    writeln!(w).unwrap();
    writeln!(w, "use crate::{{Binding, CardFormat, Core, DeviceKind, Role, RolePrefix, System, Vendor}};")
        .unwrap();
    writeln!(w).unwrap();

    emit_systems(w, data)?;
    emit_cores(w, data, clocks, kinds)?;
    table(
        w,
        "Registered save roles that are compared whole, sorted by name.",
        "ROLES",
        "Role",
        &data.roles.roles,
        |r| {
            format!(
                "Role {{ name: {}, description: {}, common: {}, systems: {} }}",
                lit(&r.role),
                lit(&r.description),
                r.common,
                lits(&r.systems)
            )
        },
    );

    table(
        w,
        "Numbered-socket prefixes, sorted by prefix.",
        "ROLE_PREFIXES",
        "RolePrefix",
        &data.roles.prefixes,
        |p| {
            format!(
                "RolePrefix {{ prefix: {}, description: {}, systems: {} }}",
                lit(&p.prefix),
                lit(&p.description),
                lits(&p.systems)
            )
        },
    );

    table(
        w,
        "Card formats, in the order the Memory Cards specification lists them.",
        "CARD_FORMATS",
        "CardFormat",
        &data.card_formats,
        |f| {
            let dirent = f.dirent_len.map_or_else(|| "None".to_owned(), |n| format!("Some({n})"));
            format!(
                "CardFormat {{ name: {}, dirent_len: {dirent}, block_size: {}, notes: {} }}",
                lit(&f.format),
                f.block_size,
                lit(&f.notes)
            )
        },
    );

    table(
        w,
        "The spec-owned `device_kind` vocabulary.",
        "DEVICE_KINDS",
        "DeviceKind",
        &data.device_kinds,
        |k| format!("DeviceKind {{ name: {}, meaning: {} }}", lit(&k.value), lit(&k.meaning)),
    );

    table(w, "The spec-owned `binding` vocabulary.", "BINDINGS", "Binding", &data.bindings, |b| {
        format!("Binding {{ name: {}, bound_to: {} }}", lit(&b.value), lit(&b.bound_to))
    });

    table(w, "Assigned names in the `x` tree, sorted by name.", "VENDORS", "Vendor", &data.vendors, |v| {
        let holder = if v.vendor.eq_ignore_ascii_case("none") {
            "None".to_owned()
        } else {
            format!("Some({})", lit(&v.vendor))
        };
        format!(
            "Vendor {{ name: {}, reserved: {}, holder: {holder}, notes: {} }}",
            lit(&v.name),
            v.kind.trim().eq_ignore_ascii_case("reserved"),
            lit(&v.notes)
        )
    });

    write_and_format(path, &out)
}

/// One const per system, then the table built out of them, so the two cannot drift.
fn emit_systems(w: &mut String, data: &Registries) -> Result<(), String> {
    let system_names = const_names(data.systems.iter().map(|s| s.slug.as_str()))?;
    writeln!(w, "/// A named const per listed system, for the consumers that know which one they mean.")
        .unwrap();
    writeln!(w, "pub mod systems {{").unwrap();
    writeln!(w, "    use crate::System;\n").unwrap();
    for (s, name) in data.systems.iter().zip(&system_names) {
        if s.aliases.is_empty() {
            writeln!(w, "    /// {}.", s.name).unwrap();
        } else {
            writeln!(w, "    /// {} — also seen as {}.", s.name, s.aliases.join(", ")).unwrap();
        }
        writeln!(
            w,
            "    pub const {name}: System = System {{ slug: {}, name: {}, aliases: {} }};",
            lit(&s.slug),
            lit(&s.name),
            lits(&s.aliases),
        )
        .unwrap();
    }
    writeln!(w, "}}\n").unwrap();

    let systems: Vec<_> = data.systems.iter().zip(&system_names).collect();
    table(
        w,
        "Every system slug, sorted by slug so lookups can binary-search.",
        "SYSTEMS",
        "System",
        &systems,
        |(_, name)| format!("systems::{name}"),
    );

    Ok(())
}

/// The same shape as the systems above: a const each, then the table built out of them. It
/// costs nothing — a const has no symbol of its own, so a consumer naming one materialises that
/// core alone and leaves the table dead.
fn emit_cores(w: &mut String, data: &Registries, clocks: &Clocks, kinds: Vec<&str>) -> Result<(), String> {
    // The same shape as the systems above: a const each, then the table built out of them. It
    // costs nothing — a const has no symbol of its own, so a consumer naming one materialises that
    // core alone and leaves the table dead.
    let core_names = const_names(data.cores.iter().map(|c| c.slug.as_str()))?;
    let cores: Vec<_> = data.cores.iter().zip(kinds).zip(&core_names).collect();
    writeln!(w, "/// A named const per listed core, so a producer that knows which core it is can say so")
        .unwrap();
    writeln!(w, "/// without a lookup — and without linking the whole table.").unwrap();
    writeln!(w, "pub mod cores {{").unwrap();
    writeln!(w, "    use crate::{{ClockLayout, Core, CoreKind}};\n").unwrap();
    for ((c, kind), name) in &cores {
        writeln!(w, "    /// {} — {}.", c.name, c.systems.join(", ")).unwrap();
        writeln!(
            w,
            "    pub const {name}: Core = Core {{ slug: {}, name: {}, kind: CoreKind::{kind}, \
             systems: {}, aliases: {}, clock: {} }};",
            lit(&c.slug),
            lit(&c.name),
            lits(&c.systems),
            lits(&c.aliases),
            clock(&c.slug, clocks)?,
        )
        .unwrap();
    }
    writeln!(w, "}}\n").unwrap();

    table(w, "Every known emulator core, sorted by slug.", "CORES", "Core", &cores, |(_, name)| {
        format!("cores::{name}")
    });

    Ok(())
}

/// Writes the file and runs rustfmt over it, so the sync check and the format check agree.
fn write_and_format(path: &Path, out: &str) -> Result<(), String> {
    // The last table is followed by a blank line from `table`; trim it so the file ends cleanly.
    let out = out.trim_end().to_owned() + "\n";
    std::fs::write(path, out).map_err(|e| format!("{}: {e}", path.display()))?;

    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(path)
        .status()
        .map_err(|e| format!("running rustfmt: {e}"))?;
    if !status.success() {
        return Err(format!("rustfmt failed on {}", path.display()));
    }
    Ok(())
}
