//! Turning the registry JSON into the static tables `one-saves-registry` ships.

use std::fmt::Write as _;
use std::path::Path;

use crate::registry::Registries;

/// A Rust string literal.
fn lit(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

/// A Rust slice of string literals.
fn lits(items: &[String]) -> String {
    format!("&[{}]", items.iter().map(|i| lit(i)).collect::<Vec<_>>().join(", "))
}

/// Writes one static table: a doc comment, the array header, a row per item, and the close.
fn table<T>(w: &mut String, doc: &str, name: &str, ty: &str, items: &[T], row: impl Fn(&T) -> String) {
    writeln!(w, "/// {doc}").unwrap();
    writeln!(w, "pub(crate) static {name}: [{ty}; {}] = [", items.len()).unwrap();
    for item in items {
        writeln!(w, "    {},", row(item)).unwrap();
    }
    writeln!(w, "];\n").unwrap();
}

fn core_kind(kind: &str) -> Result<&'static str, String> {
    match kind {
        "libretro" => Ok("Libretro"),
        "mister" => Ok("MiSTer"),
        "openfpga" => Ok("OpenFpga"),
        other => Err(format!("{other:?} is not a core kind")),
    }
}

/// Writes the generated tables, then formats them so the file is byte-stable.
///
/// Formatting here rather than leaving it to a later `cargo fmt` is what lets CI regenerate and
/// diff: without it the sync check and the format check would contradict each other.
///
/// Long, but flat: seven independent emitters in a row, with no branching between them. Splitting
/// it would put a seam somewhere the data does not have one.
#[allow(clippy::too_many_lines)]
pub fn write_rust(data: &Registries, path: &Path) -> Result<(), String> {
    // A core kind that is not one of the three is a registry change this generator has not been
    // taught, so it is checked before anything is written rather than producing a file that will
    // not compile.
    let kinds: Vec<&str> = data.cores.iter().map(|c| core_kind(&c.kind)).collect::<Result<_, _>>()?;

    let mut out = String::new();
    let w = &mut out;
    writeln!(w, "// @generated by `cargo xtask registries`. Do not edit by hand.").unwrap();
    writeln!(w, "//").unwrap();
    writeln!(w, "// The JSON under `data/` is itself synced from the registry pages at docs.1retro.com,")
        .unwrap();
    writeln!(w, "// so a change starts there, lands in the JSON, and reaches this file last.").unwrap();
    writeln!(w).unwrap();
    writeln!(
        w,
        "use crate::{{Binding, CardFormat, Core, CoreKind, DeviceKind, Role, RolePrefix, System, Vendor}};"
    )
    .unwrap();
    writeln!(w).unwrap();

    table(
        w,
        "Every system slug, sorted by slug so lookups can binary-search.",
        "SYSTEMS",
        "System",
        &data.systems,
        |s| {
            format!(
                "System {{ slug: {}, name: {}, aliases: {} }}",
                lit(&s.slug),
                lit(&s.name),
                lits(&s.aliases)
            )
        },
    );

    let cores: Vec<_> = data.cores.iter().zip(kinds).collect();
    table(w, "Every known emulator core, sorted by slug.", "CORES", "Core", &cores, |(c, kind)| {
        format!(
            "Core {{ slug: {}, name: {}, kind: CoreKind::{kind}, systems: {}, aliases: {} }}",
            lit(&c.slug),
            lit(&c.name),
            lits(&c.systems),
            lits(&c.aliases)
        )
    });

    table(
        w,
        "Registered save roles that are compared whole, sorted by name.",
        "ROLES",
        "Role",
        &data.roles.roles,
        |r| {
            format!(
                "Role {{ name: {}, description: {}, common: {}, systems: {} }}",
                lit(&r.role),
                lit(&r.description),
                r.common,
                lits(&r.systems)
            )
        },
    );

    table(
        w,
        "Numbered-socket prefixes, sorted by prefix.",
        "ROLE_PREFIXES",
        "RolePrefix",
        &data.roles.prefixes,
        |p| {
            format!(
                "RolePrefix {{ prefix: {}, description: {}, systems: {} }}",
                lit(&p.prefix),
                lit(&p.description),
                lits(&p.systems)
            )
        },
    );

    table(
        w,
        "Card formats, in the order the Memory Cards specification lists them.",
        "CARD_FORMATS",
        "CardFormat",
        &data.card_formats,
        |f| {
            let dirent = f.dirent_len.map_or_else(|| "None".to_owned(), |n| format!("Some({n})"));
            format!(
                "CardFormat {{ name: {}, dirent_len: {dirent}, notes: {} }}",
                lit(&f.format),
                lit(&f.notes)
            )
        },
    );

    table(
        w,
        "The spec-owned `device_kind` vocabulary.",
        "DEVICE_KINDS",
        "DeviceKind",
        &data.device_kinds,
        |k| format!("DeviceKind {{ name: {}, meaning: {} }}", lit(&k.value), lit(&k.meaning)),
    );

    table(w, "The spec-owned `binding` vocabulary.", "BINDINGS", "Binding", &data.bindings, |b| {
        format!("Binding {{ name: {}, bound_to: {} }}", lit(&b.value), lit(&b.bound_to))
    });

    table(w, "Assigned names in the `x` tree, sorted by name.", "VENDORS", "Vendor", &data.vendors, |v| {
        let holder = if v.vendor.eq_ignore_ascii_case("none") {
            "None".to_owned()
        } else {
            format!("Some({})", lit(&v.vendor))
        };
        format!(
            "Vendor {{ name: {}, reserved: {}, holder: {holder}, notes: {} }}",
            lit(&v.name),
            v.kind.trim().eq_ignore_ascii_case("reserved"),
            lit(&v.notes)
        )
    });

    // The last table is followed by a blank line from `table`; trim it so the file ends cleanly.
    let out = out.trim_end().to_owned() + "\n";
    std::fs::write(path, out).map_err(|e| format!("{}: {e}", path.display()))?;

    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(path)
        .status()
        .map_err(|e| format!("running rustfmt: {e}"))?;
    if !status.success() {
        return Err(format!("rustfmt failed on {}", path.display()));
    }
    Ok(())
}
