#!/usr/bin/env python3
"""Generates the registry crate's static tables from the vendored JSON."""
import json, pathlib

DATA = pathlib.Path("/Users/hansl/Sources/one-retro/one-saves/crates/one-saves-registry/data")
OUT = DATA.parent / "src/generated.rs"


def s(text):
    """A Rust string literal."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def strs(items):
    return "&[" + ", ".join(s(i) for i in items) + "]"


load = lambda name: json.loads((DATA / f"{name}.json").read_text())

systems = sorted(load("systems"), key=lambda e: e["slug"])
cores = sorted(load("cores"), key=lambda e: e["slug"])
roles_doc = load("roles")
roles = sorted(roles_doc["roles"], key=lambda e: e["role"])
prefixes = sorted(roles_doc["prefixes"], key=lambda e: e["prefix"])
vendors = sorted(load("vendors"), key=lambda e: e["name"])
formats = load("card-formats")
kinds = load("device-kinds")
bindings = load("bindings")

KIND = {"libretro": "Libretro", "mister": "MiSTer", "openfpga": "OpenFpga"}

out = []
w = out.append
w("// @generated by `cargo xtask sync-registries` from ../data/*.json. Do not edit by hand.")
w("//")
w("// The JSON under `data/` is itself synced from the registry pages at docs.1retro.com, so a")
w("// change starts there, lands in the JSON, and reaches this file last.")
w("")
w("use crate::{Binding, CardFormat, Core, CoreKind, DeviceKind, Role, RolePrefix, System, Vendor};")
w("")
w("/// Every system slug, sorted by slug so lookups can binary-search.")
w(f"pub(crate) static SYSTEMS: [System; {len(systems)}] = [")
for e in systems:
    w(f"    System {{ slug: {s(e['slug'])}, name: {s(e['name'])}, aliases: {strs(e['aliases'])} }},")
w("];")
w("")
w("/// Every known emulator core, sorted by slug.")
w(f"pub(crate) static CORES: [Core; {len(cores)}] = [")
for e in cores:
    w(
        f"    Core {{ slug: {s(e['slug'])}, name: {s(e['name'])}, kind: CoreKind::{KIND[e['kind']]}, "
        f"systems: {strs(e['systems'])}, aliases: {strs(e['aliases'])} }},"
    )
w("];")
w("")
w("/// Registered save roles that are compared whole, sorted by name.")
w(f"pub(crate) static ROLES: [Role; {len(roles)}] = [")
for e in roles:
    w(
        f"    Role {{ name: {s(e['role'])}, description: {s(e['description'])}, "
        f"common: {str(e['common']).lower()}, systems: {strs(e['systems'])} }},"
    )
w("];")
w("")
w("/// Numbered-socket prefixes, sorted by prefix.")
w(f"pub(crate) static ROLE_PREFIXES: [RolePrefix; {len(prefixes)}] = [")
for e in prefixes:
    w(
        f"    RolePrefix {{ prefix: {s(e['prefix'])}, description: {s(e['description'])}, "
        f"systems: {strs(e['systems'])} }},"
    )
w("];")
w("")
w("/// Card formats, in the order the Memory Cards specification lists them.")
w(f"pub(crate) static CARD_FORMATS: [CardFormat; {len(formats)}] = [")
for e in formats:
    dirent = "None" if e["dirent_len"] is None else f"Some({e['dirent_len']})"
    w(f"    CardFormat {{ name: {s(e['format'])}, dirent_len: {dirent}, notes: {s(e['notes'])} }},")
w("];")
w("")
w("/// The spec-owned `device_kind` vocabulary.")
w(f"pub(crate) static DEVICE_KINDS: [DeviceKind; {len(kinds)}] = [")
for e in kinds:
    w(f"    DeviceKind {{ name: {s(e['value'])}, meaning: {s(e['meaning'])} }},")
w("];")
w("")
w("/// The spec-owned `binding` vocabulary.")
w(f"pub(crate) static BINDINGS: [Binding; {len(bindings)}] = [")
for e in bindings:
    w(f"    Binding {{ name: {s(e['value'])}, bound_to: {s(e['bound_to'])} }},")
w("];")
w("")
w("/// Assigned names in the `x` tree, sorted by name.")
w(f"pub(crate) static VENDORS: [Vendor; {len(vendors)}] = [")
for e in vendors:
    reserved = str(e["kind"].strip().lower() == "reserved").lower()
    holder = "None" if e["vendor"].strip().lower() == "none" else f"Some({s(e['vendor'])})"
    w(f"    Vendor {{ name: {s(e['name'])}, reserved: {reserved}, holder: {holder}, notes: {s(e['notes'])} }},")
w("];")
w("")

OUT.write_text("\n".join(out))

# Format the result, so a regenerated file is byte-identical to the committed one and
# `cargo fmt --check` stays clean. Without this the CI sync check and the fmt check disagree.
import subprocess

subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=True)
print(f"wrote and formatted {OUT}")
print(f"  {len(systems)} systems, {len(cores)} cores, {len(roles)} roles, {len(prefixes)} prefixes,")
print(f"  {len(formats)} card formats, {len(kinds)} device kinds, {len(bindings)} bindings, {len(vendors)} vendors")
